### PR TITLE
fix: enhanced JsonRpcError handling and message formatting

### LINKED ISSUE #3658: Refactor createJsonRpcError to be static and move to utils module
## Description

The `createJsonRpcError` method in the `RpcMethodDispatcher` class (packages/relay/src/lib/dispatcher/rpcMethodDispatcher.ts) is currently an instance method but doesn't use any class state or properties.

This method should be either:

- Made static since it's not related to the dispatcher's state
- Or potentially moved to the utils module so it can be reused by other components

## Proposed Changes

- Refactor `createJsonRpcError` to be a static method
- Consider migrating it to the utils module for better code reusability
- Update any references to this method throughout the codebase

### PR DESCRIPTION
**Pull request by quiet-node**
### Description:
This PR improves JsonRpcError handling by standardizing message formatting to prevent request ID duplication and turning `createJsonRpcError()` to `JsonRpcError.newWithRequestId` static method for clarity. 

### Changes
- Prevent duplicate requestId prefixes in error messages by adding validation in the JsonRpcError constructor
- Rename `createJsonRpcError` to `newJsonRpcErrorWithRequestId` to better convey its purpose
- Move error creation method to the Utils class for better organization
- Add comprehensive test coverage for both changes

Fixes #3658

### CODE REVIEW

File: packages/relay/src/utils.ts [hunk 1]
```diff
@@ -212,4 +213,23 @@ export class Utils {
     // No configuration, use default behavior
     return [...rpcParams, requestDetails];
   }
+
+  /**
+   * Creates a new JsonRpcError with the request ID attached to assist with tracing and debugging.
+   *
+   * @param error - The original JsonRpcError instance to bind the request ID to
```
Comment (konstantinabl) [inline packages/relay/src/utils.ts:220]: Should we add the param types here in the docs? In other places we have done so and I usually add them, maybe we can discuss but its best to stick to a unified approach?

Comment (acuarica) [reply packages/relay/src/utils.ts:220]: > Should we add the param types here in the docs?

I guess it's duplicating the param definitions already provided in the function/method. If that changes, then we need to change it also here.

> maybe we can discuss but its best to stick to a unified approach?

Definitely.

Comment (quiet-node) [reply packages/relay/src/utils.ts]: Gotcha okay good catch let's stick to the current approach for now. Updated.

**Review by konstantinabl — DISMISSED** [review]

File: packages/relay/src/utils.ts [hunk 2]
```diff
@@ -212,4 +213,23 @@ export class Utils {
...
+
+  /**
+   * Creates a new JsonRpcError with the request ID attached to assist with tracing and debugging.
+   *
+   * @param {JsonRpcError} error - The original JsonRpcError instance to bind the request ID to
+   * @param {string} requestId - The unique identifier of the request that generated this error
+   * @returns A new JsonRpcError instance with identical properties but with the request ID
+   *          prefixed to the error message
+   */
+  public static newJsonRpcErrorWithRequestId(error: JsonRpcError, requestId: string): JsonRpcError {
```
Comment (acuarica) [inline packages/relay/src/utils.ts:225]: I think this would be better placed in `JsonRpcError` class itself. It's easier to understand and more cohesive (no unrelated stuff in the `Utils` class). And given it would be part of `JsonRpcError` class, then it could be renamed to `newWithRequestId` or `withRequestId`.

File: packages/relay/src/lib/dispatcher/rpcMethodDispatcher.ts [hunk 3]
```diff
@@ -169,24 +169,24 @@ export class RpcMethodDispatcher {
 
     // If error is already a JsonRpcError, use it directly
     if (error instanceof JsonRpcError) {
-      return this.createJsonRpcError(error, requestDetails.requestId);
+      return Utils.newJsonRpcErrorWithRequestId(error, requestDetails.requestId);
```
Comment (acuarica) [inline packages/relay/src/lib/dispatcher/rpcMethodDispatcher.ts:172]: no more `this` yay :)

**Review by acuarica — COMMENTED** [review]
nice stuff! left a suggestion

**Review by acuarica — DISMISSED** [review]
Actually, I'll approve it, feel free to implement the suggestion or discard it.

File: packages/relay/src/utils.ts [hunk 4]
```diff
@@ -10,6 +10,7 @@ import { Logger } from 'pino';
 import { hexToASCII, prepend0x, strip0x } from './formatters';
 import constants, { TracerType } from './lib/constants';
 import { RPC_LAYOUT, RPC_PARAM_LAYOUT_KEY } from './lib/decorators';
+import { JsonRpcError } from './lib/errors/JsonRpcError';
```
Comment (acuarica) [inline packages/relay/src/utils.ts:13]: nit: leftover, remove

wondering why doesn't the linter catch this kind thing.

File: packages/relay/tests/lib/utils.spec.ts [hunk 5]
```diff
@@ -10,6 +10,7 @@ import { ASCIIToHex, prepend0x } from '../../src/formatters';
 import constants, { TracerType } from '../../src/lib/constants';
 import { RPC_PARAM_LAYOUT_KEY } from '../../src/lib/decorators/rpcParamLayoutConfig.decorator';
 import { RPC_LAYOUT } from '../../src/lib/decorators/rpcParamLayoutConfig.decorator';
+import { JsonRpcError } from '../../src/lib/errors/JsonRpcError';
```
Comment (acuarica) [inline packages/relay/tests/lib/utils.spec.ts:13]: nit: leftover, remove

File: packages/relay/src/lib/errors/JsonRpcError.ts [hunk 6]
```diff
@@ -10,8 +10,33 @@ export class JsonRpcError {
 
   constructor(args: { code: number; message: string; data?: string }, requestId?: string) {
     this.code = args.code;
-    this.message = requestId ? `[${constants.REQUEST_ID_STRING}${requestId}] ` + args.message : args.message;
     this.data = args.data;
+
+    const hasRequestId = requestId && !args.message.includes(constants.REQUEST_ID_STRING);
+    this.message = hasRequestId ? `[${constants.REQUEST_ID_STRING}${requestId}] ${args.message}` : args.message;
```
Comment (acuarica) [inline packages/relay/src/lib/errors/JsonRpcError.ts:16]: Sweet, I definitely like it better this way.

I see that almost all usages of this constructor don't pass the `requestId` argument. There is one in `validators.ts` and the other in `webSocketServer.ts` (this one actually passes `undefined`). So if we want to go one step further, I'd move this logic into `newWithRequestId` and update the call sites.

File: packages/relay/tests/lib/utils.spec.ts (hunk 5 above)
Comment (quiet-node) [reply packages/relay/tests/lib/utils.spec.ts:13]: Good catch! Updated!

File: packages/relay/src/utils.ts (hunk 4 above)
Comment (quiet-node) [reply packages/relay/src/utils.ts:13]: Good catch! Updated

**Review by simzzz — APPROVED** [review]
LGTM
