### PR TITLE
fix: convert trace value from tinybars to weibars in debug APIs

### LINKED ISSUE #4763: `debug_traceTransaction` returns `value` in tinybars (8 decimals) instead of weibars (18 decimals)
### Expected Behavior
The `value` field should be returned in **weibars (18 decimals)** to maintain consistency with other Ethereum JSON-RPC APIs like `eth_getTransactionByHash`, `eth_getBlock`, etc.

According to Hedera's decimal precision model: 
- HAPI / JSON-RPC / EVM → 8 decimals (tinybars)
- `msg.value` in JSON-RPC → 18 decimals (weibars)

The debug/trace APIs should follow the same convention as other JSON-RPC APIs and return values in weibars.

### Actual Behavior We See Currently
When calling `debug_traceTransaction` with the `callTracer` tracer, the `value` field in the response is returned in **tinybars (8 decimal precision)** instead of **weibars (18 decimal precision)**.

This affects both the top-level trace result and all nested `calls` in the trace output.

### 1. Query `eth_getTransactionByHash` (returns correct 18 decimal weibars)

```bash
curl -X POST https://mainnet.hashio.io/api \
  -H "Content-Type: application/json" \
  -d '{
    "jsonrpc": "2.0",
    "method": "eth_getTransactionByHash",
    "params": ["0x1dd1253240aab9ee8e49c8b8d8f4044240200145a002a6b457b4233fa70c4438"],
    "id": 1
  }'
```

**Result:**
```json
{
  "result": {
    "from": "0xf56a15af2e461ae36e29ed21bdea75e6e12eb04e",
    "to": "0x00000000000000000000000000000000002e7a5d",
    "value": "0x8ac7230489e80000",
    ... 
  }
}
```

### 2. Query `debug_traceTransaction` (returns incorrect 8 decimal tinybars)

```bash
curl -X POST https://mainnet.hashio.io/api \
  -H "Content-Type: application/json" \
  -d '{
    "jsonrpc": "2.0",
    "method":  "debug_traceTransaction",
    "params": ["0x1dd1253240aab9ee8e49c8b8d8f4044240200145a002a6b457b4233fa70c4438", {"tracer": "callTracer"}],
    "id": 1
  }'
```

**Result:**
```json
{
  "result": {
    "type": "CALL",
    "from": "0xf56a15af2e461ae36e29ed21bdea75e6e12eb04e",
    "to": "0x00000000000000000000000000000000002e7a5d",
    "value": "0x3b9aca00",
    "calls": [
      {
        "type": "CALL",
        "from": "0x00000000000000000000000000000000002e7a5d",
        "to": "0x0000000000000000000000000000000000163b59",
        "value": "0x3b9aca00",
        ... 
      },
      ...
    ],
    ... 
  }
}
```

### 3. Verify raw Mirror Node data (source of truth - tinybars)

```bash
curl "https://mainnet.mirrornode.hedera.com/api/v1/contracts/results/0x1dd1253240aab9ee8e49c8b8d8f4044240200145a002a6b457b4233fa70c4438"
```

**Result:**
```json
{
  "amount":  1000000000,
  ... 
}
```

```bash
curl "https://mainnet.mirrornode.hedera.com/api/v1/contracts/results/0x1dd1253240aab9ee8e49c8b8d8f4044240200145a002a6b457b4233fa70c4438/actions"
```

**Result:**
```json
{
  "actions": [
    {
      "value": 1000000000,
      ...
    },
    ... 
  ]
}
```

## Evidence Summary

| Source | Field | Value | Decimal Interpretation |
|--------|-------|-------|------------------------|
| Mirror Node `/contracts/results/...` | `amount` | `1000000000` | 10 HBAR in tinybars (10⁹) |
| Mirror Node `/contracts/results/.../actions` | `value` | `1000000000` | 10 HBAR in tinybars (10⁹) |
| `eth_getTransactionByHash` | `value` | `0x8ac7230489e80000` | 10 HBAR in weibars (10¹⁹) ✅ |
| `debug_traceTransaction` | `value` | `0x3b9aca00` | **Raw tinybars, not converted** ❌ |

### The Math

```
eth_getTransactionByHash value: 0x8ac7230489e80000 = 10,000,000,000,000,000,000 (10^19 wei) = 10 HBAR ✅
debug_traceTransaction value:    0x3b9aca00         = 1,000,000,000 (10^9 tinybars)          = 10 HBAR ❌

Expected conversion: tinybars × TINYBAR_TO_WEIBAR_COEF (10^10) = weibars
1,000,000,000 × 10,000,000,000 = 10,000,000,000,000,000,000 = 0x8ac7230489e80000
```

### Affected APIs
- `debug_traceTransaction` with `callTracer`
- `debug_traceBlockByNumber` with `callTracer` (uses the same underlying methods)

### Impact
This bug causes incorrect `value` amounts to be displayed in transaction traces, which can lead to: 
- Debugging tools showing 10 billion times smaller values than actual
- Incorrect accounting in analytics/monitoring systems that consume trace data
- Confusion when comparing trace output with other RPC endpoints

### Hedera network

mainnet

### Version

latest commit on main(1589d1f0ccae9ac9aba2aeb260f41e3b5e455469)

### Operating system

None

### PR DESCRIPTION
**Pull request by kpachhai**
### Description

This PR fixes a bug where `debug_traceTransaction` and `debug_traceBlockByNumber` APIs were returning the `value` field in **tinybars (8 decimal precision)** instead of **weibars (18 decimal precision)**, causing inconsistency with other JSON-RPC APIs. 

### The Problem

The `value` field in debug trace responses was being returned as raw tinybar values from the mirror node without applying the `tinybarsToWeibars` conversion. This resulted in values being 10^10 times smaller than expected. 

| API | Value Returned | Unit |
|-----|----------------|------|
| `eth_getTransactionByHash` | `0x8ac7230489e80000` | weibars (correct ✅) |
| `debug_traceTransaction` (before fix) | `0x3b9aca00` | tinybars (incorrect ❌) |
| `debug_traceTransaction` (after fix) | `0x8ac7230489e80000` | weibars (correct ✅) |

### The Fix

Applied `tinybarsToWeibars` conversion in two locations in `packages/relay/src/lib/debug.ts`:

1. **`callTracer()`** - converts `amount` from contract results endpoint
2. **`formatActionsResult()`** - converts `action.value` from actions endpoint

This ensures consistency with other JSON-RPC APIs like `eth_getTransactionByHash`, `eth_getBlock`, etc.

### Related issue(s)

Fixes #4763 

### Manual Testing

Tested against mainnet transaction `0x1dd1253240aab9ee8e49c8b8d8f4044240200145a002a6b457b4233fa70c4438`:

**Before fix:**
```bash
curl -X POST http://localhost:7546 \
  -H "Content-Type: application/json" \
  -d '{
    "jsonrpc": "2.0",
    "method": "debug_traceTransaction",
    "params": ["0x1dd1253240aab9ee8e49c8b8d8f4044240200145a002a6b457b4233fa70c4438", {"tracer": "callTracer"}],
    "id": 1
  }' | jq '.result.value'

# Output: "0x3b9aca00" (incorrect - tinybars)
```

**After fix:**
```bash
curl -X POST http://localhost:7546 \
  -H "Content-Type: application/json" \
  -d '{
    "jsonrpc": "2.0",
    "method": "debug_traceTransaction",
    "params": ["0x1dd1253240aab9ee8e49c8b8d8f4044240200145a002a6b457b4233fa70c4438", {"tracer":  "callTracer"}],
    "id": 1
  }' | jq '.result.value'

# Output: "0x8ac7230489e80000" (correct - weibars)
```

**Verification against `eth_getTransactionByHash`:**
```bash
curl -X POST http://localhost:7546 \
  -H "Content-Type: application/json" \
  -d '{
    "jsonrpc": "2.0",
    "method": "eth_getTransactionByHash",
    "params": ["0x1dd1253240aab9ee8e49c8b8d8f4044240200145a002a6b457b4233fa70c4438"],
    "id": 1
  }' | jq '.result.value'

# Output: "0x8ac7230489e80000" (matches debug trace after fix ✅)
```

### Nested Calls

Also verified that nested calls in the trace have correct values:
```bash
curl -X POST http://localhost:7546 \
  -H "Content-Type: application/json" \
  -d '{
    "jsonrpc": "2.0",
    "method": "debug_traceTransaction",
    "params": ["0x1dd1253240aab9ee8e49c8b8d8f4044240200145a002a6b457b4233fa70c4438", {"tracer":  "callTracer"}],
    "id": 1
  }' | jq '.result.calls[1].value'

# Output: "0x8ac7230489e80000" (correct - weibars)
```

### CODE REVIEW

**Comment by Ferparishuertas** [comment]
thanks @kpachhai for the report and fix.
Isnt this issue more focused on changing the precision in MN? ( i had it on my todos)

We can "patch" this to unify the relay behaviour, but the source should store in 18 decimal precision ( indepently of hbar deci mals)
BTW  will add it to next sprint, for review

File: packages/relay/src/lib/debug.ts [hunk 1]
```diff
@@ -270,7 +270,10 @@ export class DebugImpl implements Debug {
           gasUsed: numberTo0x(action.gas_used),
           input: contract?.bytecode ?? action.input,
           output: contract?.runtime_bytecode ?? action.result_data,
-          value: numberTo0x(action.value),
+          value: (() => {
+            const weibarValue = tinybarsToWeibars(action.value);
+            return weibarValue == null ? DebugImpl.zeroHex : numberTo0x(weibarValue);
+          })(),
         };
```
Comment (quiet-node) [inline packages/relay/src/lib/debug.ts]: Would it make sense to change it to the following so it’s a little cleaner?

```suggestion
value: numberTo0x(tinybarsToWeibars(action.value) ?? DebugImpl.zeroHex)
```

File: packages/relay/src/lib/debug.ts [hunk 2]
```diff
@@ -461,7 +464,8 @@ export class DebugImpl implements Debug {
 
       const { resolvedFrom, resolvedTo } = await this.resolveMultipleAddresses(from, to, requestDetails);
 
-      const value = amount === 0 ? DebugImpl.zeroHex : numberTo0x(amount);
+      const weibarAmount = tinybarsToWeibars(amount);
+      const value = weibarAmount == null ? DebugImpl.zeroHex : numberTo0x(weibarAmount);
```
Comment (quiet-node) [inline packages/relay/src/lib/debug.ts]: same here

```suggestion
const value = numberTo0x(tinybarsToWeibars(amount)) ?? DebugImpl.zeroHex;
```

**Review by quiet-node — COMMENTED** [review]
LG but some feedback

File: packages/relay/tests/lib/debug.spec.ts [hunk 3]
```diff
@@ -576,6 +576,84 @@ describe('Debug API Test Suite', async function () {
             );
           });
         });
+
+        describe('tinybars to weibars conversion', async function () {
```
[the remark this answers is not in the document]
Comment (kpachhai) [reply packages/relay/tests/lib/debug.spec.ts]: Done.

File: packages/relay/src/lib/debug.ts (hunk 2 above)
Comment (kpachhai) [reply packages/relay/src/lib/debug.ts]: Refactored as above `const value = numberTo0x(tinybarsToWeibars(amount) ?? 0);`

**Review by quiet-node — COMMENTED** [review]
The implementation LG but tests seem to be failing failing
